/*Queries that provide answers to the questions from all projects.*/

SELECT * FROM ANIMALS WHERE NAME LIKE '%mon';
SELECT NAME FROM ANIMALS WHERE date_of_birth  BETWEEN '2016-01-01' AND '2019-12-31';
SELECT NAME FROM ANIMALS WHERE NEUTERED = TRUE AND ESCAPE_ATTEMPTS < 3;
SELECT DATE_OF_BIRTH FROM ANIMALS WHERE NAME = 'Agumon' OR  NAME = 'Pikachu';
SELECT NAME, ESCAPE_ATTEMPTS FROM ANIMALS WHERE WEIGHT > 10.5;
SELECT NAME FROM ANIMALS WHERE NEUTERED = TRUE;
SELECT NAME FROM ANIMALS WHERE NAME != 'Gabumon';
SELECT NAME FROM ANIMALS WHERE WEIGHT >= 10.4 AND WEIGHT <= 17.3;
