/* Database schema to keep the structure of entire database. */

CREATE TABLE ANIMALS (
    ID INT GENERATED BY DEFAULT AS IDENTITY, 
    NAME VARCHAR(20) NOT NULL, 
    DATE_OF_BIRTH DATE, 
    ESCAPE_ATTEMPTS INT DEFAULT 0 NOT NULL, 
    NEUTERED BOOLEAN DEFAULT FALSE NOT NULL, 
    WEIGHT DECIMAL NOT NULL
);

ALTER TABLE ANIMALS ADD SPICIES VARCHAR(40);

/* WEDNESDAY */

-- Create a table named owners with the following columns: 
CREATE TABLE OWNERS(id SERIAL PRIMARY KEY, full_name VARCHAR(81), age INT);

-- Create a table named species with the following columns: 
CREATE TABLE species (id SERIAL PRIMARY KEY, name VARCHAR(20));

-- Modify animals table: 
    --  Make sure that id is set as autoincremented PRIMARY KEY
    ALTER TABLE animals ALTER COLUMN id SET NOT NULL;
    ALTER TABLE animals ADD CONSTRAINT animals_pk PRIMARY KEY (id);
    -- Remove column species
    ALTER TABLE animals DROP COLUMN species;
    -- Add column species_id which is a foreign key referencing species table
    ALTER TABLE animals ADD species_id INT;
    ALTER TABLE animals ADD CONSTRAINT animal_fk FOREIGN KEY (species_id) REFERENCES species(id);
    -- Add column owner_id which is a foreign key referencing the owners table
    ALTER TABLE animals ADD owner_id INT;
    ALTER TABLE animals ADD CONSTRAINT owners_fk FOREIGN KEY (owner_id) REFERENCES owners(id);

    /*Thursday*/
    -- Create a table named vets 
    CREATE TABLE vets(id INT GENERATED ALWAYS AS IDENTITY, name VARCHAR(40), age INT, date_of_graduation DATE);
    -- Create a "join table" called specializations
    CREATE TABLE specializations (species_id INT, vets_id INT);
    -- Create a "join table" called visits
    CREATE TABLE visits (animals_id INT, vets_id INT, date DATE);

    /* Monday week 2*/

    CREATE INDEX animal_id_asc ON visits(animal_id ASC);

    CREATE INDEX vet_id_asc ON visits(vet_id ASC);

    CREATE INDEX email_asc ON owners(email ASC);










